name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy-to-minikube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package

      - name: Setup Minikube
        uses: medyagh/setup-minikube@master

      - name: Build and push image to Minikube
        run: |
          eval $(minikube -p minikube docker-env)
          docker build -t demo:1.0 .
          docker images

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl get pods
