name: Deploy to minikube
on: workflow_dispatch
env:
  DOCKER_USERNAME: ${{vars.DOCKER_NAME}}
  DOCKER_PASSWORD: ${{secrets.PASSWORD}}
  DOCKER_IMAGE: shubham4775/demo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package
          
      - name: Docker Build
        run: |
          docker build -t $DOCKER_IMAGE:${{github.sha}} .
          docker tag $DOCKER_IMAGE:${{github.sha}} $DOCKER_IMAGE:latest
          
      - name: Docker Push
        run: |
          docker push $DOCKER_IMAGE:${{github.sha}}
          docker push $DOCKER_IMAGE:latest

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest
          
      - name: Setup Minikube
        run: |
          minikube start
          kubectl config use-context minikube
          
      - name: Deployment k8s
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
